# Generated by Django 4.1 on 2022-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='charts')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('weight', models.IntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('exam_date', models.DateField()),
                ('exam_start', models.TimeField()),
                ('exam_end', models.TimeField()),
                ('days', models.ManyToManyField(to='easy_vahed.weekday')),
            ],
        ),
    ]
