# Generated by Django 4.1 on 2022-08-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof', '0001_initial'),
        ('easy_vahed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.university'),
        ),
        migrations.AddField(
            model_name='chart',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.major'),
        ),
        migrations.AddField(
            model_name='chart',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.university'),
        ),
    ]
