# Generated by Django 4.1 on 2022-08-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_vahed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
