# Generated by Django 4.1 on 2022-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
        ('easy_vahed', '0003_remove_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(to='prof.major'),
        ),
    ]
