"""
Django settings for uniar_bot project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$b__9-ev1*w59647ayq&a29t90r7r&1m9bb2k)(4t#30_0cg0g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prof.apps.ProfConfig',
    'easy_vahed.apps.EasyVahedConfig',
    'easy_deadline.apps.EasyDeadlineConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uniar_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uniar_bot.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "example"
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = 'static/'
STATIC_URL = 'static/'

MEDIA_ROOT = ''
MEDIA_URL = ''

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Telegram Messages
TELEGRAM_MESSAGES = {
    'blind_start': 'سلام چطوری؟\n'
                   'برای اینکه از من سواستفاده کنی باید *دانشگاهتو* بهم بگی :)))',

    'register_university': 'رشتتو بهم بگو بلا :))',
    'register_major': 'ورودی چه *سالی* هستی عنن:؟',
    'register_done': 'تامام شد تبریک میگم بهت :) /start',
    'expired': 'خیلی کندی :/',
    'menu': 'شل کن بدو :)',
    'easy_vahed': 'انتخاب کن یالا!!',
    'choose_courses': 'لطفا درساتو انتخاب کن.\n'
                      'تعداد *واحد* انتخاب شده: *{weight}*',
    'has_conflict': 'درس {c1} با درس {c2} به دلیل {reason} تداخل دارد!',
    'courses_solution': 'اگه درس *{c}* رو حذف کنی می‌تونی این انتخاب‌هارو داشته باشی...',
    'has_not_conflict': 'همه‌چی اوکیه! بردار عشق کن ;)',
    'wanna_add_to_profile': 'می‌خوای اینا به پروفایلت اضافه بشه؟',
    'added_to_profile': 'اضافه شد!',
    'cancel_adding_to_profile': 'حله :)',
    'profile': '{name} - {major} - {university} - {year}\n'
               'دروس برداشته شده برای این ترم',
    'profile_courses': '*{name}* {prof} {weight} واحد',
    'sum_weight': 'در مجموع *{sum}* واحد برداشتی!',
    'easy_deadline_main': 'برای کدوم درست می‌خوای *ددلاین* ست کنی؟',
    'easy_deadline_course': 'دیتیل مربوط به ددلاینتو وارد کن.\n'
                            'کورس: *{name}*',
    'easy_deadline_name': 'لطفا *نام* تمرینت رو وارد کن!',
    'easy_deadline_deadline': 'لطفا *ددلاین* تمرینت رو وارد کن.'

}

STATES = {
    'blind_start': 0,
    'register_university': 1,
    'register_major': 2,
    'register_year': 3,
    'register_done': 4,
    'menu': 5,
    'easy_vahed': 6,
    'choose_courses': 7,
    'add_course_to_profile': 8,
    'easy_deadline': 9,
    'easy_deadline_courses': 10,
    'easy_deadline_name': 11,
}
